language: node_js
node_js:
  - '4'
  - '5'
  - '6'
git:
  depth: 5
script:
  - npm run check:src
  - npm run build
after_success:
  - npm run test:coverage
  - npm run coverage
branches:
  only:
    - master
cache:
  directories:
    - node_modules